config/routes.rb
Rails.application.routes.draw do
  # BROWSER
  resources :payments
  resources :credit_cards, except: [:index]
  resources :orders
  resources :schedules
  resources :restaurant_food_items
  resources :order_food_items
  resources :restaurants
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'restaurants#index'

  # API
  scope module: :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :restaurants do
        resources :restaurant_food_items
      end

      resources :orders do
        resources :order_food_items
      end
      resources :descriptions, only: [:create, :update, :show, :destroy]
      resources :users, only: [:create, :show]
      post 'auth/login', to: 'authentication#authenticate'
    end
  end
end

app/models/food_items/order_food_item.rb
class OrderFoodItem < FoodItem
end

app/controllers/api/v1/order_food_items_controller.rb
module Api
  module V1
    class OrderFoodItemsController < ::Api::BaseController
      before_action :set_food_item, only: [:show, :edit, :update, :destroy]
      before_action :set_attributes, only: [:create, :update]

      # GET /food_items
      # GET /food_items.json
      def index
        json_response(current_order.order_food_items)
      end

      # GET /food_items/1
      # GET /food_items/1.json
      def show
        json_response(@food_item)
      end

      # GET /food_items/new
      def new
        json_response(current_order.order_food_items.new)
      end

      # GET /food_items/1/edit
      def edit
        json_response(@food_item)
      end

      # POST /food_items
      # POST /food_items.json
      def create
        json_response(current_order.order_food_items.create!(food_item_params), :created)
      end

      # PATCH/PUT /food_items/1
      # PATCH/PUT /food_items/1.json
      def update
        json_response(@food_item.update!(food_item_params))
      end

      # DELETE /food_items/1
      # DELETE /food_items/1.json
      def destroy
        @food_item.destroy!
        head :no_content
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_food_item
          @food_item = current_order.order_food_items.find_by(uuid: params[:id])
        end

        def set_attributes
          if food_item_params[:description_attributes] && food_item_params[:description_attributes][:id]
            food_item_params[:description_attributes][:id] = Description.find_by(uuid: food_item_params[:description_attributes][:id]).id
          end
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def food_item_params
          params.require(:order_food_item).permit(:name, :price, :image_url, description_attributes: [:id, :content, :_destroy])
        end
    end
  end
end

app/controllers/order_food_items_controller.rb
class OrderFoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = OrderFoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = OrderFoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = OrderFoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to order_food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = OrderFoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:order_food_item).permit(:name, :price, :description_id, :image_url,
                                            description_attributes: [:id, :content, :_destroy])
    end
end

app/views/order_food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', order_food_items_path %>

app/views/order_food_items/index.html.erb
<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.image_url %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_order_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_order_food_item_path %>

app/views/order_food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', order_food_items_path %>

app/views/order_food_items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @food_item.image_url %>
</p>

<%= link_to 'Edit', edit_order_food_item_path(@food_item) %> |
<%= link_to 'Back', order_food_items_path %>